<?php
/*

forcesessiontimeout

*/

function forcesessiontimeout_help($path, $arg) {
	  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#forcesessiontimeout":
      $output = '<p>'.  t("Set an absolute timeout for logged in users") .'</p>';
      break;
  }
  return $output;
}

function forcesessiontimeout_admin() {
  $form = array();

  $form['forcesessiontimeout_maxmins'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of minutes'),
    '#default_value' => variable_get('forcesessiontimeout_maxmins', 0),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t("The maximum number of minutes a session can be active. (0 = disabled)."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function forcesessiontimeout_menu() {

  $items = array();

  $items['admin/settings/forcesessiontimeout'] = array(
    'title' => 'Force Session Timeout settings',
    'description' => 'Description of your settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forcesessiontimeout_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function forcesessiontimeout_admin_validate($form, &$form_state) {
  $maxmins = $form_state['values']['forcesessiontimeout_maxmins'];
  if (!is_numeric($maxmins)) {
    form_set_error('forcesessiontimeout_maxmins', t('You must enter an integer for the maximum number of minutes.'));
  }
  else if ($maxmins < 0) {
    form_set_error('forcesessiontimeout_maxmins', t('Maximum number of minutes must be positive.'));
  }
}


function forcesessiontimeout_init() {
	global $user;
	if($user->uid > 0){
		$maxmins = variable_get('forcesessiontimeout_maxmins', 0);
		$absolutetimeout = $user->login + ($maxmins * 60);
		
		if ($maxmins > 0 && $absolutetimeout < time()) {
			// Force the user to log out.
			module_load_include('inc', 'user', 'user.pages');
			user_logout();
		} 
	}
}


function forcesessiontimeout_uninstall() {
	variable_del('forcesessiontimeout_maxmins');
}
